### ISSUE TITLE
Issues with hass 2021.10

### ISSUE THREAD

**Issue by fredrike** [kirei/hass-chargeamps#23]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/chargeamps/__init__.py:111
Integration: chargeamps (documentation, issues)
First occurred: 18:42:46 (1 occurrences)
Last logged: 18:42:46

Error during setup of component chargeamps
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 254, in _async_setup_component
    result = await task
  File "/config/custom_components/chargeamps/__init__.py", line 111, in async_setup
    for cp in await client.get_chargepoints():
  File "/usr/local/lib/python3.9/site-packages/chargeamps/external.py", line 82, in get_chargepoints
    response = await self._get(request_uri)
  File "/usr/local/lib/python3.9/site-packages/chargeamps/external.py", line 66, in _get
    await self._ensure_token()
  File "/usr/local/lib/python3.9/site-packages/chargeamps/external.py", line 54, in _ensure_token
    token_payload = jwt.decode(self._token, verify=False)
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/jwt/api_jwt.py", line 86, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().

**Comment by jschlyter** [comment]
Thanks for the report, [fixed release](https://github.com/kirei/hass-chargeamps/releases/tag/v1.5.2) published.

**Comment by jschlyter** [comment]
FWI, JWT `iat` issue at ChargeAmps has caseId 23168

**Comment by jschlyter** [comment]
@DanielOrneling They are looking into it. Strange I did not get this error on 2021.10.2 - what version did you try? Could it be fixed in the JWT library used in 2021.10?

**Comment by DanielOrneling** [comment]
And it's working again just as expected :)
________________________________
