### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by vlumikero** [kirei/hass-chargeamps#30]
Hi,

I’m getting the following error when the component is trying to start up. 

Any idea what it could be?

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/chargeamps/__init__.py", line 119, in async_setup
    handler = ChargeampsHandler(hass, client, charge_point_ids, readonly, scan_interval)
  File "/config/custom_components/chargeamps/__init__.py", line 158, in __init__
    self.default_charge_point_id = charge_point_ids[0]
IndexError: list index out of range

**Comment by vlumikero** [comment]
I think the listing of chargepoints didn’t return anything, at least when I tried it with the Swagger UI. When I specified the chargepoint id, it worked.

**Comment by vlumikero** [comment]
I think the listing of chargepoints didn’t return anything, at least when I tried it with the Swagger UI. When I specified the chargepoint id, it worked.

Hämta Outlook för iOS<https://aka.ms/o0ukef>
________________________________
Från: Jakob Schlyter ***@***.***>
Skickat: Thursday, July 7, 2022 1:01:28 PM
Till: kirei/hass-chargeamps ***@***.***>
Kopia: vlumikero ***@***.***>; State change ***@***.***>
Ämne: Re: [kirei/hass-chargeamps] Index out of range (Issue #30)


What was the issue?
