### ISSUE TITLE
[547107617904] 400, message='Bad Request', url=URL('https://eapi.charge.space/api/v4/chargepoints/(redacted)/connectors/2/settings')

### ISSUE THREAD

**Issue by patrik-sp** [kirei/hass-chargeamps#36]
I get the following error message when I try to turn on or off the schuko outlet on my Halo. Worth noting is that I have the "real" OCPP version (OCPP 1.6J) of Halo connected over LAN cable. All other actions seem to work as expected without any errors.

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/chargeamps/__init__.py:231
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 13:47:36 (2 occurrences)
Last logged: 13:50:48

[547107617904] 400, message='Bad Request', url=URL('https://eapi.charge.space/api/v4/chargepoints/(redacted)/connectors/2/settings')
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
    await result
  File "/config/custom_components/chargeamps/switch.py", line 86, in async_turn_on
    await self.handler.set_connector_mode(
  File "/config/custom_components/chargeamps/__init__.py", line 231, in set_connector_mode
    await self.client.set_chargepoint_connector_settings(settings)
  File "/usr/local/lib/python3.10/site-packages/chargeamps/external.py", line 155, in set_chargepoint_connector_settings
    await self._put(request_uri, json=payload)
  File "/usr/local/lib/python3.10/site-packages/chargeamps/external.py", line 76, in _put
    return await self._session.put(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 643, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://eapi.charge.space/api/v4/chargepoints/(redacted)/connectors/2/settings')

```

**Comment by patrik-sp** [comment]
Resolved with latest release (v1.8.3). Closing issue.
